package com.skinhub.view;

import com.skinhub.controller.algorithm.Sorting;
import com.skinhub.controller.algorithm.Operations;
import com.skinhub.controller.algorithm.Search;
import com.skinhub.model.ProductModel;
import com.skinhub.util.Validation;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 * Main class for the Skin Care Hub application.
 * Manages the user interface and core functionalities.
 * Uses CardLayout to switch between different screens.
 * Initializes instances of Operations, Sorting, and Search classes.
 * Interacts with the user interface components to display and manage product data.
 * 
 * @author: Chewan Regmi
 * LMU ID 23056535
 */
public class SkinCare extends javax.swing.JFrame {
    private List<ProductModel> productList;
    private Operations operations;
    private java.awt.CardLayout cardLayout;
    private Sorting sorting;
    private Search search;

    /**
     * Creates new form SkinCare
     */
    public SkinCare() {
        productList = new ArrayList<ProductModel>();
        operations = new Operations();
        sorting = new Sorting();
        search = new Search();
        initComponents();
        initializeLayout(); // Set up CardLayout and add screens
        startProgress(); // Show loading screen and initiate progress  
        initializeData();
        initializeComboBox();
        clearInputFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        pnlLoginLeft = new javax.swing.JPanel();
        lblLoginLogo = new javax.swing.JLabel();
        lblLoginSlogan = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        txtFldLoginUsername = new javax.swing.JTextField();
        pwdFldLogin = new javax.swing.JPasswordField();
        lblLoginSubTitle = new javax.swing.JLabel();
        lblLoginForgotPwd = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        adminPanel = new javax.swing.JPanel();
        adminBodyPanel = new javax.swing.JPanel();
        productDataLabel = new javax.swing.JLabel();
        productDetailsPanel = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        productIDLabel = new javax.swing.JLabel();
        productIdTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        brandLabel = new javax.swing.JLabel();
        brandComboBox = new javax.swing.JComboBox<>();
        categoryLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        productDetailLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        productScrollPane = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        AddProduct = new javax.swing.JButton();
        clearProductButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        RemoveProduct = new javax.swing.JButton();
        sortByPriceBtn = new javax.swing.JButton();
        sortByIdBtn = new javax.swing.JButton();
        sortByNameBtn = new javax.swing.JButton();
        viewProductButton = new javax.swing.JButton();
        adminHeaderPanel = new javax.swing.JPanel();
        searchBarTxtField = new javax.swing.JTextField();
        logoLbl = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        homeBodyPanel = new javax.swing.JPanel();
        screenPanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        homeScrollPane = new javax.swing.JScrollPane();
        homeTextArea = new javax.swing.JTextArea();
        headerPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        searchBarTextField = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        productScreenPanel = new javax.swing.JPanel();
        homeTextField = new javax.swing.JTextField();
        sunScreenLabel = new javax.swing.JLabel();
        moisturizerLabel = new javax.swing.JLabel();
        faceMaskLabel = new javax.swing.JLabel();
        cleanserLabel = new javax.swing.JLabel();
        tonerLabel = new javax.swing.JLabel();
        allProductLabel = new javax.swing.JLabel();
        serumLabel = new javax.swing.JLabel();
        tonerNameLabel = new javax.swing.JLabel();
        serumNameLabel = new javax.swing.JLabel();
        cleanserNameLabel = new javax.swing.JLabel();
        sunScreenNameLabel = new javax.swing.JLabel();
        moisturizerNameLabel = new javax.swing.JLabel();
        faceMaskNameLabel = new javax.swing.JLabel();
        loadingPanel = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();
        pleaseWaitLabel = new javax.swing.JLabel();
        loadingProgressBar = new javax.swing.JProgressBar();

        loginPanel.setBackground(new java.awt.Color(218, 249, 222));
        loginPanel.setMaximumSize(new java.awt.Dimension(1000, 700));
        loginPanel.setMinimumSize(new java.awt.Dimension(1000, 700));
        loginPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        pnlLoginLeft.setBackground(new java.awt.Color(220, 245, 226));
        pnlLoginLeft.setMaximumSize(new java.awt.Dimension(570, 514));
        pnlLoginLeft.setMinimumSize(new java.awt.Dimension(570, 514));

        lblLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/loading background.jpg"))); // NOI18N

        lblLoginSlogan.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblLoginSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginSlogan.setText("A daily skincare routine is a daily act of self-love");

        javax.swing.GroupLayout pnlLoginLeftLayout = new javax.swing.GroupLayout(pnlLoginLeft);
        pnlLoginLeft.setLayout(pnlLoginLeftLayout);
        pnlLoginLeftLayout.setHorizontalGroup(
            pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLeftLayout.createSequentialGroup()
                .addGroup(pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLoginLeftLayout.setVerticalGroup(
            pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLeftLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblLoginSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblLoginTitle.setBackground(new java.awt.Color(224, 244, 230));
        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(241, 115, 115));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Sign in to Skin Care Hub");

        txtFldLoginUsername.setBackground(new java.awt.Color(245, 241, 241));
        txtFldLoginUsername.setForeground(new java.awt.Color(0, 51, 51));
        txtFldLoginUsername.setText("admin");
        txtFldLoginUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32), 2), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(234, 192, 32))); // NOI18N

        pwdFldLogin.setBackground(new java.awt.Color(246, 242, 242));
        pwdFldLogin.setForeground(new java.awt.Color(0, 51, 51));
        pwdFldLogin.setText("admin");
        pwdFldLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32), 2), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(234, 192, 32))); // NOI18N

        lblLoginSubTitle.setBackground(new java.awt.Color(204, 255, 204));
        lblLoginSubTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblLoginSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginSubTitle.setText("Please enter your login details below using this app.");

        lblLoginForgotPwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoginForgotPwd.setForeground(new java.awt.Color(0, 51, 51));
        lblLoginForgotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginForgotPwd.setText("Forgot your password?");

        btnLogin.setBackground(new java.awt.Color(204, 255, 204));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(255, 0, 0));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoginLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoginTitle)
                                .addGap(93, 93, 93)
                                .addComponent(lblLoginError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLoginForgotPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(1130, 1130, 1130))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblLoginError))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(txtFldLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginForgotPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(1000, 700));
        mainPanel.setMinimumSize(new java.awt.Dimension(1000, 700));

        mainTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        mainTabbedPane.setMaximumSize(new java.awt.Dimension(1000, 700));
        mainTabbedPane.setMinimumSize(new java.awt.Dimension(1000, 700));
        mainTabbedPane.setPreferredSize(new java.awt.Dimension(1000, 700));

        adminPanel.setMaximumSize(new java.awt.Dimension(1000, 665));
        adminPanel.setMinimumSize(new java.awt.Dimension(1000, 665));
        adminPanel.setPreferredSize(new java.awt.Dimension(1000, 665));

        adminBodyPanel.setBackground(new java.awt.Color(223, 248, 230));
        adminBodyPanel.setPreferredSize(new java.awt.Dimension(1000, 596));

        productDataLabel.setBackground(new java.awt.Color(255, 255, 255));
        productDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        productDataLabel.setText("Products");

        productDetailsPanel.setBackground(new java.awt.Color(195, 250, 208));

        productNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        productNameLabel.setText("Name :");

        productNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        productIDLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        productIDLabel.setText("ID :");

        productIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        priceLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        priceLabel.setText("Price :");

        weightLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        weightLabel.setText("Weight :");

        weightTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        brandLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        brandLabel.setText("Brand :");

        brandComboBox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anua", "Aurel Derma", "BIOBALANCE", "Ethicare ", "truederma" }));

        categoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        categoryLabel.setText("Category :");

        categoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cleanser", "Toner", "Face Serum", "Pigmentation", "SunScreen" }));

        productDetailLabel.setBackground(new java.awt.Color(204, 255, 255));
        productDetailLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productDetailLabel.setText("Product Details");

        priceTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout productDetailsPanelLayout = new javax.swing.GroupLayout(productDetailsPanel);
        productDetailsPanel.setLayout(productDetailsPanelLayout);
        productDetailsPanelLayout.setHorizontalGroup(
            productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productDetailsPanelLayout.createSequentialGroup()
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productDetailsPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(productDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productDetailsPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(productNameLabel)
                        .addGap(40, 40, 40)
                        .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productDetailsPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(productIDLabel)
                        .addGap(62, 62, 62)
                        .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productDetailsPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(priceLabel)
                        .addGap(59, 59, 59)
                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productDetailsPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(weightLabel)
                        .addGap(49, 49, 49)
                        .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(productDetailsPanelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(categoryLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(productDetailsPanelLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(brandLabel)
                            .addGap(49, 49, 49)
                            .addComponent(brandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        productDetailsPanelLayout.setVerticalGroup(
            productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(productDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productNameLabel)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productIDLabel)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLabel)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productDetailsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(brandLabel))
                    .addComponent(brandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(productDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        productTable.setBackground(new java.awt.Color(250, 246, 246));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Name", "Price", "Brand", "Weight", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productScrollPane.setViewportView(productTable);

        AddProduct.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddProduct.setText("Add Product");
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });

        clearProductButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearProductButton.setText("Clear Field");
        clearProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearProductButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UpdateButton.setText("Update Product");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        RemoveProduct.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RemoveProduct.setText("Remove Product");
        RemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveProductActionPerformed(evt);
            }
        });

        sortByPriceBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sortByPriceBtn.setText("Sort by price ");
        sortByPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByPriceBtnActionPerformed(evt);
            }
        });

        sortByIdBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sortByIdBtn.setText("Sort by Id ");
        sortByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByIdBtnActionPerformed(evt);
            }
        });

        sortByNameBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sortByNameBtn.setText("Sort by Name");
        sortByNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByNameBtnActionPerformed(evt);
            }
        });

        viewProductButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewProductButton.setText("View Product");
        viewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminBodyPanelLayout = new javax.swing.GroupLayout(adminBodyPanel);
        adminBodyPanel.setLayout(adminBodyPanelLayout);
        adminBodyPanelLayout.setHorizontalGroup(
            adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminBodyPanelLayout.createSequentialGroup()
                .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                        .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminBodyPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(adminBodyPanelLayout.createSequentialGroup()
                                .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(AddProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE))
                                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(clearProductButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(RemoveProduct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sortByNameBtn)
                                        .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(sortByIdBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sortByPriceBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(viewProductButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminBodyPanelLayout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(productScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(productDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        adminBodyPanelLayout.setVerticalGroup(
            adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminBodyPanelLayout.createSequentialGroup()
                .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                        .addComponent(productDataLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortByPriceBtn)
                            .addComponent(UpdateButton))
                        .addGap(28, 28, 28)
                        .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddProduct)
                            .addComponent(sortByIdBtn)))
                    .addComponent(productDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(adminBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortByNameBtn)
                        .addGap(19, 19, 19)
                        .addComponent(viewProductButton))
                    .addGroup(adminBodyPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(RemoveProduct)
                        .addGap(18, 18, 18)
                        .addComponent(clearProductButton)))
                .addGap(110, 110, 110))
        );

        adminHeaderPanel.setBackground(new java.awt.Color(245, 250, 218));

        searchBarTxtField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/logo.jpg"))); // NOI18N

        adminLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        adminLabel.setText("Hello Admin");

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminHeaderPanelLayout = new javax.swing.GroupLayout(adminHeaderPanel);
        adminHeaderPanel.setLayout(adminHeaderPanelLayout);
        adminHeaderPanelLayout.setHorizontalGroup(
            adminHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminHeaderPanelLayout.createSequentialGroup()
                .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchBarTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(searchBtn)
                .addGap(194, 194, 194)
                .addComponent(btnLogout)
                .addGap(51, 51, 51))
        );
        adminHeaderPanelLayout.setVerticalGroup(
            adminHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminHeaderPanelLayout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(adminHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminHeaderPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(adminHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchBarTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addComponent(adminHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainTabbedPane.addTab("Admin", adminPanel);

        homePanel.setBackground(new java.awt.Color(245, 245, 220));

        homeBodyPanel.setBackground(new java.awt.Color(255, 255, 250));

        screenPanel.setBackground(new java.awt.Color(227, 252, 217));

        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/products.jpg"))); // NOI18N
        homeLabel.setMaximumSize(new java.awt.Dimension(478, 387));
        homeLabel.setMinimumSize(new java.awt.Dimension(478, 387));
        homeLabel.setPreferredSize(new java.awt.Dimension(478, 387));

        homeTextArea.setBackground(new java.awt.Color(227, 252, 217));
        homeTextArea.setColumns(20);
        homeTextArea.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        homeTextArea.setRows(5);
        homeTextArea.setText("         Welcome !!\t\n               To \n         Skin Care Hub \n\n          Self Care \n             Starts with \n                  Skin care !!\n\n          Healthy skin\n                reflects \n         overall wellness!");
        homeTextArea.setBorder(null);
        homeScrollPane.setViewportView(homeTextArea);

        javax.swing.GroupLayout screenPanelLayout = new javax.swing.GroupLayout(screenPanel);
        screenPanel.setLayout(screenPanelLayout);
        screenPanelLayout.setHorizontalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenPanelLayout.createSequentialGroup()
                .addComponent(homeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        screenPanelLayout.setVerticalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenPanelLayout.createSequentialGroup()
                .addGroup(screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeBodyPanelLayout = new javax.swing.GroupLayout(homeBodyPanel);
        homeBodyPanel.setLayout(homeBodyPanelLayout);
        homeBodyPanelLayout.setHorizontalGroup(
            homeBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBodyPanelLayout.createSequentialGroup()
                .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeBodyPanelLayout.setVerticalGroup(
            homeBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBodyPanelLayout.createSequentialGroup()
                .addComponent(screenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(245, 245, 220));

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchButton.setText("Search");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nameLabel.setText("Skin Care Hub");

        searchBarTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(nameLabel)
                .addGap(85, 85, 85)
                .addComponent(searchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nameLabel))))
                .addContainerGap())
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Home", homePanel);

        productScreenPanel.setBackground(new java.awt.Color(213, 250, 207));
        productScreenPanel.setMaximumSize(new java.awt.Dimension(1000, 650));
        productScreenPanel.setMinimumSize(new java.awt.Dimension(1000, 650));
        productScreenPanel.setPreferredSize(new java.awt.Dimension(1000, 650));

        homeTextField.setBackground(new java.awt.Color(251, 244, 244));
        homeTextField.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        homeTextField.setText("Beauty is about being comfortable in your skin");

        sunScreenLabel.setBackground(new java.awt.Color(204, 255, 204));
        sunScreenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/sunscreen .jpg"))); // NOI18N
        sunScreenLabel.setMaximumSize(new java.awt.Dimension(245, 165));
        sunScreenLabel.setMinimumSize(new java.awt.Dimension(245, 165));
        sunScreenLabel.setOpaque(true);
        sunScreenLabel.setPreferredSize(new java.awt.Dimension(245, 165));

        moisturizerLabel.setBackground(new java.awt.Color(204, 255, 204));
        moisturizerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/Moisturizer.jpg"))); // NOI18N
        moisturizerLabel.setMaximumSize(new java.awt.Dimension(245, 165));
        moisturizerLabel.setMinimumSize(new java.awt.Dimension(245, 165));
        moisturizerLabel.setOpaque(true);
        moisturizerLabel.setPreferredSize(new java.awt.Dimension(245, 165));

        faceMaskLabel.setBackground(new java.awt.Color(51, 255, 164));
        faceMaskLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/facemask.jpg"))); // NOI18N
        faceMaskLabel.setMaximumSize(new java.awt.Dimension(245, 165));
        faceMaskLabel.setMinimumSize(new java.awt.Dimension(245, 165));
        faceMaskLabel.setOpaque(true);
        faceMaskLabel.setPreferredSize(new java.awt.Dimension(245, 165));

        cleanserLabel.setBackground(new java.awt.Color(204, 255, 204));
        cleanserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/cleanse.jpg"))); // NOI18N
        cleanserLabel.setOpaque(true);

        tonerLabel.setBackground(new java.awt.Color(153, 255, 153));
        tonerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/toner.jpg"))); // NOI18N
        tonerLabel.setOpaque(true);

        allProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        allProductLabel.setText("All products");

        serumLabel.setBackground(new java.awt.Color(204, 255, 204));
        serumLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/serum.jpg"))); // NOI18N
        serumLabel.setOpaque(true);

        tonerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tonerNameLabel.setText("Toner");
        tonerNameLabel.setToolTipText("");

        serumNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        serumNameLabel.setText("Serum");

        cleanserNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cleanserNameLabel.setText("Cleanser ");

        sunScreenNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sunScreenNameLabel.setText("Sun Screen");

        moisturizerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moisturizerNameLabel.setText("Moisturizer");

        faceMaskNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        faceMaskNameLabel.setText("Face Mask");

        javax.swing.GroupLayout productScreenPanelLayout = new javax.swing.GroupLayout(productScreenPanel);
        productScreenPanel.setLayout(productScreenPanelLayout);
        productScreenPanelLayout.setHorizontalGroup(
            productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productScreenPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(faceMaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cleanserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                                .addComponent(moisturizerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                                .addComponent(allProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tonerLabel)
                        .addGap(88, 88, 88)))
                .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productScreenPanelLayout.createSequentialGroup()
                        .addComponent(sunScreenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                        .addComponent(serumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(cleanserNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tonerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(serumNameLabel)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScreenPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(faceMaskNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moisturizerNameLabel)
                .addGap(184, 184, 184)
                .addComponent(sunScreenNameLabel)
                .addGap(118, 118, 118))
            .addGroup(productScreenPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(homeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productScreenPanelLayout.setVerticalGroup(
            productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(allProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productScreenPanelLayout.createSequentialGroup()
                        .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(productScreenPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cleanserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(productScreenPanelLayout.createSequentialGroup()
                                .addComponent(serumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45)))
                        .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tonerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(serumNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cleanserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tonerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moisturizerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faceMaskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunScreenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sunScreenNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moisturizerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faceMaskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Product", productScreenPanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));

        loadingPanel.setBackground(new java.awt.Color(205, 248, 216));
        loadingPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loadingPanel.setMaximumSize(new java.awt.Dimension(1000, 700));
        loadingPanel.setMinimumSize(new java.awt.Dimension(1000, 700));
        loadingPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skinhub/resources/loading background.jpg"))); // NOI18N

        pleaseWaitLabel.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        pleaseWaitLabel.setText("Please wait !!!");

        loadingProgressBar.setBackground(new java.awt.Color(176, 238, 176));

        javax.swing.GroupLayout loadingPanelLayout = new javax.swing.GroupLayout(loadingPanel);
        loadingPanel.setLayout(loadingPanelLayout);
        loadingPanelLayout.setHorizontalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPanelLayout.createSequentialGroup()
                .addGroup(loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loadingPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(backgroundLabel))
                    .addGroup(loadingPanelLayout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(pleaseWaitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPanelLayout.createSequentialGroup()
                .addGap(0, 274, Short.MAX_VALUE)
                .addComponent(loadingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        loadingPanelLayout.setVerticalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pleaseWaitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Initialize the layout and add screens to the CardLayout.
     
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loadingPanel, "LoadingScreen");
        getContentPane().add(loginPanel, "LoginScreen");
        getContentPane().add(mainPanel, "MainScreen");
        
        // Start with the loading screen
        loadScreen("LoadingScreen");
      
    }
    
    private void initializeData(){
        //adding sample product to the table
        addProduct(new ProductModel(10050, "Moisoftt",385.00 ,"Aurel Derma",(short)100,"Cleanser"));
        addProduct(new ProductModel(51848, "Peach 77",2900.00 ,"Anua",(short)250 ,"Toner"));
        addProduct(new ProductModel(64812, "SuperSerum",1685.00 ,"BIOBALANCE",(short)30 ,"Face Serum"));
        addProduct(new ProductModel(98742, "Lipidz",789.50 ,"Ethicare",(short)100 ,"Pigmentation"));
        addProduct(new ProductModel(97552, "Luxurious",900.0 ,"truederma",(short)60 ,"SunScreen"));
        updateProductTable(productList);
    }
    

    private void addProduct(ProductModel product){
        productList.add(product);
        operations.addProduct(productTable, product);
    }
    
        private void initializeComboBox() {
        
        String[] categories = {"Cleanser", "Toner", "Face Serum", "Pigmentation", "SunScreen"};
        categoryComboBox = new javax.swing.JComboBox<>(categories);

        // Brands
        String[] brands = {"Anua", "Aurel Derma", "BIOBALANCE", "Ethicare", "truederma"};
        brandComboBox = new javax.swing.JComboBox<>(brands);
       
    }
    
    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                loadingProgressBar.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the username and password input
        String username = txtFldLoginUsername.getText();
        String password = new String(pwdFldLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Please fill out the empty fields! ", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            JOptionPane.showMessageDialog(this, "wrong usernameor password ", "Incorrect input", JOptionPane.ERROR_MESSAGE);
        } // If credentials are correct, proceed to load the main screen
        else {
            JOptionPane.showMessageDialog(this, "Successfully logged in!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
        String productId = productIdTextField.getText();
        String productName = productNameTextField.getText();
        String productPrice = priceTextField.getText();
        String productWeight = weightTextField.getText();
        String productBrand = (String) brandComboBox.getSelectedItem();
        String productCategory = (String) categoryComboBox.getSelectedItem();

        if (Validation.validateProductInput(productId, productName, productPrice, productWeight, productBrand, productCategory)) {
            int productID = Integer.parseInt(productId);

            for (ProductModel product : productList) {
                if (product.getProductID() == productID) {
                    JOptionPane.showMessageDialog(this, "Product ID already exists.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            double price = Double.parseDouble(productPrice);
            short weight = Short.parseShort(productWeight);

            ProductModel newProduct = new ProductModel(productID, productName, price, productBrand, weight, productCategory);
            addProduct(newProduct);

            // Clear input fields
            clearInputFields();
            // Show success message
            JOptionPane.showMessageDialog(this, "Product added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AddProductActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        int selectedRow = productTable.getSelectedRow();
        if (selectedRow >= 0) {
            String productId = productIdTextField.getText();
            String productName = productNameTextField.getText();
            String productPrice = priceTextField.getText();
            String productWeight = weightTextField.getText();
            String productBrand = (String) brandComboBox.getSelectedItem();
            String productCategory = (String) categoryComboBox.getSelectedItem();

            if (Validation.validateProductInput(productId, productName, productPrice, productWeight, productBrand, productCategory)) {
                int productID = Integer.parseInt(productId);
                double price = Double.parseDouble(productPrice);
                short weight = Short.parseShort(productWeight);

                ProductModel updatedProduct = new ProductModel(productID, productName, price, productBrand, weight, productCategory);
                
                productList.forEach(product->{
                // check if productID exists in our productList -> update
                    if(product.getProductID() == productID){
                        product.setBrand(productBrand);
                        //............//for all attributes
                    }
                });                
                operations.updateProduct(productTable, selectedRow, updatedProduct);

                // Clear input fields
                clearInputFields();

                // Show success message
                JOptionPane.showMessageDialog(this, "Product updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a product to update.", "Update Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void RemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveProductActionPerformed
        int selectedRow = productTable.getSelectedRow();
        if (selectedRow >= 0) {
            
            //logical mistake as if we sort and after that try to remove product then it will create error
            productList.remove(selectedRow);
            //.....
            operations.deleteProduct(productTable, selectedRow);
            // Show success message
            JOptionPane.showMessageDialog(this, "Product removed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a product to remove.", "Remove Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_RemoveProductActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        pwdFldLogin.setText("");
        txtFldLoginUsername.setText("");
        loadScreen("LoginScreen"); // Load the main screen
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void sortByPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByPriceBtnActionPerformed
        List<ProductModel> sortedList = sorting.sortByPrice(productList, false);
        updateProductTable(sortedList);
    }//GEN-LAST:event_sortByPriceBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchTerm = searchBarTextField.getText().trim();
        Search search = new Search();
        ProductModel foundProduct = null;

        // Search by name
        foundProduct = search.searchByName(searchTerm, productList, 0, productList.size() - 1);

        // Check the result
        if (foundProduct != null) {
            // Update the input fields with the product details
            productIdTextField.setText(String.valueOf(foundProduct.getProductID()));
            productNameTextField.setText(foundProduct.getProductName());
            priceTextField.setText(String.valueOf(foundProduct.getPrice()));
            weightTextField.setText(String.valueOf(foundProduct.getWeight()));
            brandComboBox.setSelectedItem(foundProduct.getBrand());
            categoryComboBox.setSelectedItem(foundProduct.getCategory());

            // Update the table to show only the found product
            DefaultTableModel model = (DefaultTableModel) productTable.getModel();
            model.setRowCount(0); // Clear the table
            model.addRow(new Object[]{
                foundProduct.getProductID(),
                foundProduct.getProductName(),
                foundProduct.getPrice(),
                foundProduct.getWeight(),
                foundProduct.getBrand(),
                foundProduct.getCategory()
            });
        } else {
            JOptionPane.showMessageDialog(this, "No products found for the search term: " + searchTerm, "No Results", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void sortByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByIdBtnActionPerformed
        List<ProductModel> sortedList = sorting.sortByProductId(productList, false);
        updateProductTable(sortedList);
    }//GEN-LAST:event_sortByIdBtnActionPerformed

    private void sortByNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByNameBtnActionPerformed
        List<ProductModel> sortedList = sorting.sortByProductName(productList, false);
        updateProductTable(sortedList);
    }//GEN-LAST:event_sortByNameBtnActionPerformed

    private void clearProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearProductButtonActionPerformed
        productIdTextField.setText("");
        productNameTextField.setText("");
        priceTextField.setText("");
        weightTextField.setText("");
    }//GEN-LAST:event_clearProductButtonActionPerformed

    /**
     * Action performed when the "View Product" button is clicked.
     * Retrieves and displays the selected product's details.
     */
    private void viewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductButtonActionPerformed
        int selectedRow = productTable.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) productTable.getModel();
            int productId = (int) model.getValueAt(selectedRow, 0);
            String productName = (String) model.getValueAt(selectedRow, 1);
            double price = (double) model.getValueAt(selectedRow, 2);
            String brand = (String) model.getValueAt(selectedRow, 3);
            short weight = (short) model.getValueAt(selectedRow, 4);
            String category = (String) model.getValueAt(selectedRow, 5);

            // Populate the form fields with the product details
            productIdTextField.setText(String.valueOf(productId));
            productNameTextField.setText(productName);
            priceTextField.setText(String.valueOf(price));
            brandComboBox.setSelectedItem(brand);
            weightTextField.setText(String.valueOf(weight));
            categoryComboBox.setSelectedItem(category);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a product to view.", "No Product Selected", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_viewProductButtonActionPerformed


    private void updateProductTable(List<ProductModel> productList) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.setRowCount(0); // Clear existing rows

        for (ProductModel product : productList) {
            model.addRow(new Object[]{
                product.getProductID(),
                product.getProductName(),
                product.getPrice(),
                product.getBrand(),
                product.getWeight(),
                product.getCategory()
            });
        }
    }
    
    private void clearInputFields(){
    // Clear input fields
        productIdTextField.setText("");
        productNameTextField.setText("");
        priceTextField.setText("");
        weightTextField.setText("");
    }
    
    
    
     /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SkinCare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduct;
    private javax.swing.JButton RemoveProduct;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel adminBodyPanel;
    private javax.swing.JPanel adminHeaderPanel;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel allProductLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JComboBox<String> brandComboBox;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel cleanserLabel;
    private javax.swing.JLabel cleanserNameLabel;
    private javax.swing.JButton clearProductButton;
    private javax.swing.JLabel faceMaskLabel;
    private javax.swing.JLabel faceMaskNameLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel homeBodyPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JScrollPane homeScrollPane;
    private javax.swing.JTextArea homeTextArea;
    private javax.swing.JTextField homeTextField;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginForgotPwd;
    private javax.swing.JLabel lblLoginLogo;
    private javax.swing.JLabel lblLoginSlogan;
    private javax.swing.JLabel lblLoginSubTitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JPanel loadingPanel;
    private javax.swing.JProgressBar loadingProgressBar;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel moisturizerLabel;
    private javax.swing.JLabel moisturizerNameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pleaseWaitLabel;
    private javax.swing.JPanel pnlLoginLeft;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel productDataLabel;
    private javax.swing.JLabel productDetailLabel;
    private javax.swing.JPanel productDetailsPanel;
    private javax.swing.JLabel productIDLabel;
    private javax.swing.JTextField productIdTextField;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JPanel productScreenPanel;
    private javax.swing.JScrollPane productScrollPane;
    private javax.swing.JTable productTable;
    private javax.swing.JPasswordField pwdFldLogin;
    private javax.swing.JPanel screenPanel;
    private javax.swing.JTextField searchBarTextField;
    private javax.swing.JTextField searchBarTxtField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel serumLabel;
    private javax.swing.JLabel serumNameLabel;
    private javax.swing.JButton sortByIdBtn;
    private javax.swing.JButton sortByNameBtn;
    private javax.swing.JButton sortByPriceBtn;
    private javax.swing.JLabel sunScreenLabel;
    private javax.swing.JLabel sunScreenNameLabel;
    private javax.swing.JLabel tonerLabel;
    private javax.swing.JLabel tonerNameLabel;
    private javax.swing.JTextField txtFldLoginUsername;
    private javax.swing.JButton viewProductButton;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
